<a href="https://colab.research.google.com/github/ramanro24/Pandas-Learning/blob/main/Pandas_DataFrame_Practice_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Different way of creating dataframe

In [129]:

# Method1:  First, let's import pandas and other useful libraries
import pandas as pd
import numpy as np

# Section 1: Creating DataFrames
# Method 1: From a dictionary
data = {
    'Name': ['John', 'Alice', 'Bob', 'Emma'],
    'Age': [25, 30, 35, 28],
    'Salary': [50000, 60000, 75000, 65000],
    'Department': ['IT', 'HR', 'Finance', 'Marketing']
}
df = pd.DataFrame(data)
df

    Name  Age  Salary Department
0   John   25   50000         IT
1  Alice   30   60000         HR
2    Bob   35   75000    Finance
3   Emma   28   65000  Marketing

In [130]:
#Method 2: From list of Dictonaries:
data2= [
    {"Name":"Jonny","Age": 23 , "Salary": 3000  , "Department":"HR" },
    {"Name":"Alice","Age": 30 , "Salary": 5000, "Department":"IT"},
    {"Name":"Bob","Age" : 31 , "Salary": 5010, "Department":"IT"},
    {"Name":"Emma","Age" : 22 , "Salary": 1500, "Department": "HR"},

]

df2=pd.DataFrame(data2)
df2

    Name  Age  Salary Department
0  Jonny   23    3000         HR
1  Alice   30    5000         IT
2    Bob   31    5010         IT
3   Emma   22    1500         HR

In [103]:
# Section 2: Basic DataFrame Operations
# Selecting columns
names=df["Name"]
multiple_coulumns=df[["Name","Age", "Salary"]]
print(names)
print(multiple_coulumns)

0    Jonny
1    Alice
2      Bob
3     Emma
Name: Name, dtype: object
    Name  Age  Salary
0  Jonny   23    3000
1  Alice   30    5000
2    Bob   31    5010
3   Emma   22    1500

In [104]:
#Adding new columns:
df["Bonus"] = df["Salary"] *0.1
print(df)

    Name  Age  Salary Department  Bonus
0  Jonny   23    3000         HR  300.0
1  Alice   30    5000         IT  500.0
2    Bob   31    5010         IT  501.0
3   Emma   22    1500         HR  150.0

In [105]:
#Filtering Data:
high_salary=df[df["Salary"]> 2000]
print(high_salary)

    Name  Age  Salary Department  Bonus
0  Jonny   23    3000         HR  300.0
1  Alice   30    5000         IT  500.0
2    Bob   31    5010         IT  501.0

In [106]:
#Sorting:
df.sort_values('Age')

    Name  Age  Salary Department  Bonus
3   Emma   22    1500         HR  150.0
0  Jonny   23    3000         HR  300.0
1  Alice   30    5000         IT  500.0
2    Bob   31    5010         IT  501.0

In [107]:
#Section 3: Data Manipulations:
# Group by department and claucualte the mean of Salary:

department_group=df.groupby('Department')['Salary'].mean()
print(department_group)

Department
HR    2250.0
IT    5005.0
Name: Salary, dtype: float64

In [108]:
#Section 4: Apply function to columns:

df['Name_length']=df['Name'].apply(len)
print(df)

    Name  Age  Salary Department  Bonus  Name_length
0  Jonny   23    3000         HR  300.0            5
1  Alice   30    5000         IT  500.0            5
2    Bob   31    5010         IT  501.0            3
3   Emma   22    1500         HR  150.0            4

#Practice Questions

In [131]:
#Practice Question 1:
#Create a DataFrame with student data containing:
#- Student_ID (1001 to 1005), Name, Grade (A, B, C, etc.)
#- Score (random numbers between 60-100)


data = {
    "StudentID":[1001, 1010, 1044, 1032],
    "Name":["Jon","Anna", "Lauren", "Van"],
    "Grade":["F", "B", "A", "S"],
    "Score":[41, 88, 91, 100]
}
df=pd.DataFrame(data)
print(df)

   StudentID    Name Grade  Score
0       1001     Jon     F     41
1       1010    Anna     B     88
2       1044  Lauren     A     91
3       1032     Van     S    100

In [110]:
# a. Filter students with scores > 80
Gradeabove80=df[df['Score']>90]
print(Gradeabove80.sort_values('StudentID'))

   StudentID    Name Grade  Score
3       1032     Van     S    100
2       1044  Lauren     A     91

In [111]:
#b.  Calculate the average score per grade:
grade_per_average=df.groupby('Grade')['Score'].mean()
print(grade_per_average)

Grade
A     91.0
B     88.0
F     41.0
S    100.0
Name: Score, dtype: float64

In [112]:
# c. Add Pass/Fail column
df['Status']=df['Score'].apply(lambda x: 'Pass' if x>50 else 'Fail')
print(df)

   StudentID    Name Grade  Score Status
0       1001     Jon     F     41   Fail
1       1010    Anna     B     88   Pass
2       1044  Lauren     A     91   Pass
3       1032     Van     S    100   Pass

**Practice Question 2:**
Create a sales DataFrame with:
- Product
- Price
- Quantity
- Date
Then:


a) Calculate total revenue per product (Price * Quantity)

b) Find top 3 selling products by quantity

c) Calculate monthly sales totals (assuming multiple months of data)

"""

In [114]:
data= {
    "Product":["Rice", "Pulses", "Wheat", "Produce", "Meat", "Frozen"],
    "Price":[22, 21, 34, 21, 48, 21],
    "Quantity":[4, 2, 3, 4, 2, 4],
    "Date":["30-Jan-2024", "20-Feb-2024", "15-March-2024", "16-March-2024", "17-April-2024", "30-April-2024"]
}
df=pd.DataFrame(data)
print(df)

   Product  Price  Quantity           Date
0     Rice     22         4    30-Jan-2024
1   Pulses     21         2    20-Feb-2024
2    Wheat     34         3  15-March-2024
3  Produce     21         4  16-March-2024
4     Meat     48         2  17-April-2024
5   Frozen     21         4  30-April-2024

In [115]:
#a) Calculate total revenue per product (Price * Quantity)
df['Total Revenue']= df['Price']* df["Quantity"]
print(df)

   Product  Price  Quantity           Date  Total Revenue
0     Rice     22         4    30-Jan-2024             88
1   Pulses     21         2    20-Feb-2024             42
2    Wheat     34         3  15-March-2024            102
3  Produce     21         4  16-March-2024             84
4     Meat     48         2  17-April-2024             96
5   Frozen     21         4  30-April-2024             84

In [116]:
#b) Find top 3 selling products by quantity
top_3_products=df.sort_values('Quantity', ascending=False)
print(top_3_products.head(3))

   Product  Price  Quantity           Date  Total Revenue
0     Rice     22         4    30-Jan-2024             88
3  Produce     21         4  16-March-2024             84
5   Frozen     21         4  30-April-2024             84

In [117]:
#c) Calculate monthly sales totals (assuming multiple months of data)
df['Date']=pd.to_datetime(df['Date'], format='%d-%B-%Y', errors='coerce')
monthly_sales=df.groupby(df['Date'].dt.to_period('M'))['Total Revenue'].sum()
print(monthly_sales)

Date
2024-03    186
2024-04    180
Freq: M, Name: Total Revenue, dtype: int64

**Practice Question 3:**

Create an employee DataFrame and:

a) Find employees with above-average salary

b) Calculate department-wise statistics

c) Create a new column with years until retirement (assume 65 as retirement)

In [118]:
empdata={
    "ID":[161, 135, 106, 102],
    "Name":['Amit', 'Ritesh', 'Jon', 'Amir'],
    "Salary":[3000, 4500, 3101, 6500],
    "Department":['Finance', 'IT', 'HR', 'ML']

}
df=pd.DataFrame(empdata)
print(df)

    ID    Name  Salary Department
0  161    Amit    3000    Finance
1  135  Ritesh    4500         IT
2  106     Jon    3101         HR
3  102    Amir    6500         ML

In [119]:
#a. Find employee with above average high_salary
above_average_salary=df[df['Salary']>df['Salary'].mean()]
print(above_average_salary)

    ID    Name  Salary Department
1  135  Ritesh    4500         IT
3  102    Amir    6500         ML

In [120]:
#b. Calculate department wise statistics
department_wise_stats=df.groupby('Department')['Salary'].agg(['mean','min', 'max'])
print(department_wise_stats)

              mean   min   max
Department
Finance     3000.0  3000  3000
HR          3101.0  3101  3101
IT          4500.0  4500  4500
ML          6500.0  6500  6500

In [121]:
# Add age to the dataframe and and add the retirement columns to determine the retirement age left
df['Age']=[45,61, 59,62]
df

df['Year_Until_Retirement']=65-df['Age']
df

    ID    Name  Salary Department  Age  Year_Until_Retirement
0  161    Amit    3000    Finance   45                     20
1  135  Ritesh    4500         IT   61                      4
2  106     Jon    3101         HR   59                      6
3  102    Amir    6500         ML   62                      3

**Practice Question 4**

Create a DataFrame for an online store’s product reviews with:**

- Review_ID (e.g., R001, R002, etc.)

- Product_Name

- Rating (1 to 5)

- Review_Date (dates in 2025)

- Customer_Type (e.g., 'New', 'Returning')

Then:

a) Find products with an average rating below 3

b) Calculate the number of reviews per Customer_Type

c) Add a 'Rating_Category' column:
   - 'Excellent' for Rating = 5
   - 'Good' for Rating = 4
   - 'Average' for Rating = 3
   - 'Poor' for Rating <= 2

In [122]:
data1={
    "Review_ID":['R001', 'R002', 'R003', 'R004', 'R005', 'R006'],
    "Product_Name":[  'Rice', 'Pulses', 'Wheat', 'Produce', 'Meat', 'Frozen'],
    'Reveiew_Date':['April 2024', 'March 2024', 'August 2024', "July 2024", 'June 2024', 'Feb 2024'],
    'Customer_Type':['Non_Returning', 'Returning', 'Returning', 'Non_Returning', 'Non_Returning', 'Non_Returning'],
    'Ratings': [1,5,6,3,2,2]

}
df=pd.DataFrame(data1)
print(df)

  Review_ID Product_Name Reveiew_Date  Customer_Type  Ratings
0      R001         Rice   April 2024  Non_Returning        1
1      R002       Pulses   March 2024      Returning        5
2      R003        Wheat  August 2024      Returning        6
3      R004      Produce    July 2024  Non_Returning        3
4      R005         Meat    June 2024  Non_Returning        2
5      R006       Frozen     Feb 2024  Non_Returning        2

In [123]:
#1. Find a prodcut where average rating is below 3
average_rating=df.groupby('Product_Name')['Ratings'].mean()[lambda x: x<3]

print(average_rating)

Product_Name
Frozen    2.0
Meat      2.0
Rice      1.0
Name: Ratings, dtype: float64

In [124]:
#2.  Calculate the number of review per  customer type
review_per_customer=df.groupby('Customer_Type')['Review_ID'].count()
print(review_per_customer)

Customer_Type
Non_Returning    4
Returning        2
Name: Review_ID, dtype: int64

In [127]:
#3. Add rating columns:
df['Ratings_Category']=df['Ratings'].apply(lambda x: 'Excellent' if x==5 else ('Good' if x==4 else ('Average' if x==3 else 'Poor')))
print(df)

  Review_ID Product_Name Reveiew_Date  Customer_Type  Ratings Ratings_Category
0      R001         Rice   April 2024  Non_Returning        1             Poor
1      R002       Pulses   March 2024      Returning        5        Excellent
2      R003        Wheat  August 2024      Returning        6             Poor
3      R004      Produce    July 2024  Non_Returning        3          Average
4      R005         Meat    June 2024  Non_Returning        2             Poor
5      R006       Frozen     Feb 2024  Non_Returning        2             Poor