<a href="https://colab.research.google.com/github/ramanro24/Pandas-Learning/blob/main/Resturant_tips_using_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This project explores a restaurant's tipping dataset using Python's pandas library to perform data manipulation and analysis. The dataset contains information about customers, including the total bill, tip amount, day of the week, gender, and whether the customer smoked. Key tasks include calculating tip percentages, categorizing tips into groups such as Low, Average, Good, and Excellent based on the percentage, and adding binary values for smoker/non-smoker status. Additionally, the project explores insights like identifying which gender tips the least, categorizing customers based on their smoking behavior, and calculating the total number of customers served each day.

In [2]:
import pandas as pd
import seaborn as sns
df=sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
#Basic info of dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [7]:
#Checking the null values
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [8]:
df.nunique()

total_bill    229
tip           123
sex             2
smoker          2
day             4
time            2
size            6
dtype: int64

In [9]:
#Descriptive Statistics of datasets
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [11]:
#What are the columns in the dataset?
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [13]:
#1. How many unique days are in the dataset?
df['day'].unique()

['Sun', 'Sat', 'Thur', 'Fri']
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

In [14]:
#2. What is the average tip amount?

df['tip'].mean()

np.float64(2.99827868852459)

In [18]:
#3. What is the total revenue (sum of total bills)?
Sum_of_total_bills= df['total_bill'].sum()
Sum_of_total_bills

np.float64(4827.77)

In [21]:
#4. How many male and female customers are there?

df.groupby('sex')['sex'].count()

<ipython-input-21-b769a730938d>:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('sex')['sex'].count()

sex
Male      157
Female     87
Name: sex, dtype: int64

In [22]:
#4. How many male and female customers are there?
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [27]:
#5. What is the most common party size?
df['size'].value_counts()

size
2    156
3     38
4     37
5      5
1      4
6      4
Name: count, dtype: int64

In [29]:
#5.1 Calculate the tip percentage
df['tip_percentage']=df['tip']/df['total_bill'] *100
df.describe()

       total_bill         tip        size  tip_percentage
count  244.000000  244.000000  244.000000      244.000000
mean    19.785943    2.998279    2.569672       16.080258
std      8.902412    1.383638    0.951100        6.107220
min      3.070000    1.000000    1.000000        3.563814
25%     13.347500    2.000000    2.000000       12.912736
50%     17.795000    2.900000    2.000000       15.476977
75%     24.127500    3.562500    3.000000       19.147549
max     50.810000   10.000000    6.000000       71.034483

In [44]:
#6. Categorize tips as Low, Average, Good, Excellent based on tip percentage.

def categorize_tip(percentage):
  if percentage<10:
    return "Low"
  elif 10<= percentage <15:
    return "Average"
  elif 15<=percentage <20:
    return "Good"
  else:
    return "Exellent"

# Apply fucntion using values:
tip_categories=[]
for tip in df['tip_percentage']:
  tip_categories.append(categorize_tip(tip))
df['tip_categories']=tip_categories
df.head()

,total_bill,tip,sex,smoker,day,time,size,tip_percentage,tip_categories
0,16.99,1.01,Female,No,Sun,Dinner,2,5.944673,Low
1,10.34,1.66,Male,No,Sun,Dinner,3,16.054159,Good
2,21.01,3.50,Male,No,Sun,Dinner,3,16.658734,Good
3,23.68,3.31,Male,No,Sun,Dinner,2,13.978041,Average
4,24.59,3.61,Female,No,Sun,Dinner,4,14.680765,Average

In [45]:
#7. Create a column indicating whether a customer smoked or not using binary values (1 for smoker, 0 for non-smoker).

df['is_smoker']=df['smoker'].apply(lambda x:1 if x=="Yes" else 0)
df

,total_bill,tip,sex,smoker,day,time,size,tip_percentage,tip_categories,is_smoker
0,16.99,1.01,Female,No,Sun,Dinner,2,5.944673,Low,0
1,10.34,1.66,Male,No,Sun,Dinner,3,16.054159,Good,0
2,21.01,3.50,Male,No,Sun,Dinner,3,16.658734,Good,0
3,23.68,3.31,Male,No,Sun,Dinner,2,13.978041,Average,0
4,24.59,3.61,Female,No,Sun,Dinner,4,14.680765,Average,0
...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,20.392697,Exellent,0
240,27.18,2.00,Female,Yes,Sat,Dinner,2,7.358352,Low,1
241,22.67,2.00,Male,Yes,Sat,Dinner,2,8.822232,Low,1
242,17.82,1.75,Male,No,Sat,Dinner,2,9.820426,Low,0
243,18.78,3.00,Female,No,Thur,Dinner,2,15.974441,Good,0

#Filtering and Grouping

In [48]:
#8. Find all bills greater than $40 and their corresponding tip amounts.
df[df['total_bill']>40][['total_bill','tip']]

     total_bill    tip
59        48.27   6.73
95        40.17   4.73
102       44.30   2.50
142       41.19   5.00
156       48.17   5.00
170       50.81  10.00
182       45.35   3.50
184       40.55   3.00
197       43.11   5.00
212       48.33   9.00

In [51]:
#9. Get the average tip per day of the week.


df.groupby('day')['total_bill'].mean().sort_values(ascending=False)

<ipython-input-51-bcb1ec23ea76>:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('day')['total_bill'].mean().sort_values(ascending=False)

day
Sun     21.410000
Sat     20.441379
Thur    17.682742
Fri     17.151579
Name: total_bill, dtype: float64

In [55]:
#10.Find the day with the highest total revenue.

df.groupby('day')['total_bill'].sum().sort_values(ascending=False)

<ipython-input-55-15bdd7ef4936>:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('day')['total_bill'].sum().sort_values(ascending=False)

day
Sat     1778.40
Sun     1627.16
Thur    1096.33
Fri      325.88
Name: total_bill, dtype: float64

In [56]:
#11. What is the average tip percentage for smokers vs. non-smokers?

df.groupby('smoker')['total_bill'].mean()

<ipython-input-56-6272f668dc47>:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('smoker')['total_bill'].mean()

smoker
Yes    20.756344
No     19.188278
Name: total_bill, dtype: float64

In [57]:
#12. What is the average bill amount for each gender?

df.groupby('sex')['total_bill'].mean()

<ipython-input-57-5bcb01bc1889>:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('sex')['total_bill'].mean()

sex
Male      20.744076
Female    18.056897
Name: total_bill, dtype: float64

In [58]:
#13. What is the most common tip amount for each day?

df.groupby('day')['tip'].value_counts()

<ipython-input-58-7a8cb57a05a2>:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('day')['tip'].value_counts()

day   tip
Thur  2.00     13
      4.00      5
      1.50      4
      3.00      4
      5.00      4
               ..
Sun   6.70      0
      6.73      0
      7.58      0
      9.00      0
      10.00     0
Name: count, Length: 492, dtype: int64

In [59]:
#14. Sort the dataset by total bill in descending order.


df.sort_values(by='total_bill', ascending=False)

,total_bill,tip,sex,smoker,day,time,size,tip_percentage,tip_categories,is_smoker
170,50.81,10.00,Male,Yes,Sat,Dinner,3,19.681165,Good,1
212,48.33,9.00,Male,No,Sat,Dinner,4,18.621974,Good,0
59,48.27,6.73,Male,No,Sat,Dinner,4,13.942407,Average,0
156,48.17,5.00,Male,No,Sun,Dinner,6,10.379905,Average,0
182,45.35,3.50,Male,Yes,Sun,Dinner,3,7.717751,Low,1
...,...,...,...,...,...,...,...,...,...,...
149,7.51,2.00,Male,No,Thur,Lunch,2,26.631158,Exellent,0
111,7.25,1.00,Female,No,Sat,Dinner,1,13.793103,Average,0
172,7.25,5.15,Male,Yes,Sun,Dinner,2,71.034483,Exellent,1
92,5.75,1.00,Female,Yes,Fri,Dinner,2,17.391304,Good,1
67,3.07,1.00,Female,Yes,Sat,Dinner,1,32.573290,Exellent,1

In [60]:
#15. Find the top 5 highest tips given.
df.sort_values(by='tip', ascending=False).head(5)

,total_bill,tip,sex,smoker,day,time,size,tip_percentage,tip_categories,is_smoker
170,50.81,10.00,Male,Yes,Sat,Dinner,3,19.681165,Good,1
212,48.33,9.00,Male,No,Sat,Dinner,4,18.621974,Good,0
23,39.42,7.58,Male,No,Sat,Dinner,4,19.228818,Good,0
59,48.27,6.73,Male,No,Sat,Dinner,4,13.942407,Average,0
141,34.30,6.70,Male,No,Thur,Lunch,6,19.533528,Good,0

In [63]:
#15. Find the Gender  who tip the least with tip
# Group the gender and calcualte the mean tip
gender_tip_avg=df.groupby('sex')['tip'].mean()

#Find the gender that tipped the least
least_tip_gender= gender_tip_avg.idxmin()

least_tip_value=gender_tip_avg.min()
print(least_tip_gender)
print(least_tip_value)

Female
2.833448275862069

<ipython-input-63-3b0d03b72a57>:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  gender_tip_avg=df.groupby('sex')['tip'].mean()

In [64]:
#16. Calculate the total number of customers served each day.
df.groupby('day')['size'].sum()

<ipython-input-64-d094c3b1d929>:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('day')['size'].sum()

day
Thur    152
Fri      40
Sat     219
Sun     216
Name: size, dtype: int64

In [68]:
#17. Calcualte total number of cusomter served eachday by gender
df.groupby(['day','sex'])['size'].sum()

<ipython-input-68-08e77b6392e7>:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(['day','sex'])['size'].sum()

day   sex
Thur  Male       73
      Female     79
Fri   Male       21
      Female     19
Sat   Male      156
      Female     63
Sun   Male      163
      Female     53
Name: size, dtype: int64

In [70]:
#18. Find the average tip given for each table size
df.groupby('size')['tip'].mean()

size
1    1.437500
2    2.582308
3    3.393158
4    4.135405
5    4.028000
6    5.225000
Name: tip, dtype: float64

In [72]:
#19. Compare the total revenue between weekends and weekdays.
df.groupby('day')['total_bill'].sum()

<ipython-input-72-bc64afadff1a>:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('day')['total_bill'].sum()

day
Thur    1096.33
Fri      325.88
Sat     1778.40
Sun     1627.16
Name: total_bill, dtype: float64

In [75]:
#20. Compare the total revenue between weekends and weekdays.

df['day_type']=df['day'].apply(lambda x: 'weekend' if x == 'Sat' or x == 'Sun' else 'weekday')


df.groupby('day_type')['total_bill'].sum()

day_type
weekday    1422.21
weekend    3405.56
Name: total_bill, dtype: float64

In [76]:
correlation =df[['total_bill', 'tip', 'size']].corr()
print(correlation)

            total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000